# Generated by Django 2.2.7 on 2023-05-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230515_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
