# Generated by Django 2.2.7 on 2023-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20230520_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='price',
            new_name='fried_price',
        ),
        migrations.AddField(
            model_name='fish',
            name='steam_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
