# Generated by Django 2.2.7 on 2023-05-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20230520_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salad',
        ),
    ]
