# Generated by Django 2.2.7 on 2023-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_userorder_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='table',
            field=models.IntegerField(),
        ),
    ]
