# Generated by Django 2.2.7 on 2023-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20230531_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_no', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Table No',
                'verbose_name_plural': 'Table No',
            },
        ),
    ]
